name: Linux build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job name
  build:
    name: Linux build
    if: github.repository == 'speckdavid/symk'
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install packages
      run: sudo apt install cmake g++ make python3 autoconf automake
    
    - name: Build release
      run: ./build.py
    
    - name: Build debug
      run: ./build.py debug
