name: MacOS build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job name
  build:
    name: MacOS build
    if: github.repository == 'speckdavid/symk'
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install packages
      run: brew install cmake make python3 autoconf automake gcc
    
    - name: Build release
      run: ./build.py
    
    - name: Build debug
      run: ./build.py debug
